### PR TITLE
[WIP] Add Unet for consistency models

### PR DESCRIPTION
**Pull request by ayushtues**
Adding Unet model and conversion scripts, part of https://github.com/huggingface/diffusers/pull/3492

To-do

- [x] Add building blocks needed for the original repo Unet implementation
- [x] Conversion script for weights into diffusers + load pretrained weights into diffusers
- [x] Check if forward passes into pretrained model give same results as original repo

### CODE REVIEW

**Comment by ayushtues** [comment]
@dg845 Was able to convert the Unet into diffusers, load pretrained checkpoints and get same outputs from forward passes: 

ckpt : https://huggingface.co/ayushtues/consistency_models/tree/main

`unet = UNet2DModel.from_pretrained("ayushtues/consistency_models", subfolder="diffusers_cd_imagenet64_l2")
`

**Comment by ayushtues** [comment]
Had to add two new blocks to `unet_2d_blocks` - `AttnDownsampleBlock2D` & `AttnUpsampleBlock2D`, because I needed a resnet based down/upsampler along with attention, and the existing `AttnDownBlock2D` &`AttnUpBlock2D` just used a simple conv downsampler.

Open to suggestions on how to design this better

**Comment by dg845** [comment]
Sorry, didn't get a chance to look at this until now.

> Had to add two new blocks to unet_2d_blocks - AttnDownsampleBlock2D & AttnUpsampleBlock2D, because I needed a resnet based down/upsampler along with attention, and the existing AttnDownBlock2D &AttnUpBlock2D just used a simple conv downsampler.
> 
> Open to suggestions on how to design this better

The new blocks look fine to me. I guess I'm not the most knowledgeable about unet_2d_blocks so it might be worth it to ask the maintainers directly about the design.

Also, I have a quick question: does the conversion script support class-conditional models? I see for example in the [consistency model scripts](https://github.com/openai/consistency_models/blob/main/scripts/launch.sh) that there are some examples of training and sampling from them.

**Comment by dg845** [comment]
I took a closer look at the unet block implementations and it looks like [`SimpleCrossAttnDownBlock2D`](https://github.com/huggingface/diffusers/blob/main/src/diffusers/models/unet_2d_blocks.py#L1438)/[`SimpleCrossAttnUpBlock2D`](https://github.com/huggingface/diffusers/blob/main/src/diffusers/models/unet_2d_blocks.py#L2546) are pretty similar to `AttnDownsampleBlock2D`/`AttnUpsampleBlock2D` in having a `ResnetBlock2D`/`Attention`/`ResnetBlock2D` downsampler/upsampler pattern. Might it be possible to leverage some or all of the `SimpleCrossAttnDownBlock2D`/`SimpleCrossAttnUpBlock2D` implementation?

**Comment by ayushtues** [comment]
Sorry, I was blocked by Github for a while ( supposedly a VS code extension was generating infinite PRs 🙈 ). 

> Also, I have a quick question: does the conversion script support class-conditional models? I see for example in the [consistency model scripts](https://github.com/openai/consistency_models/blob/main/scripts/launch.sh) that there are some examples of training and sampling from them.

The current `Unet2DModel` already supports class conditioning : https://github.com/ayushtues/diffusers/blob/consistency_unet/src/diffusers/models/unet_2d.py#L223, and infact I tested this while making sure the forward passes are the same

**Comment by ayushtues** [comment]
> I took a closer look at the unet block implementations and it looks like [`SimpleCrossAttnDownBlock2D`](https://github.com/huggingface/diffusers/blob/main/src/diffusers/models/unet_2d_blocks.py#L1438)/[`SimpleCrossAttnUpBlock2D`](https://github.com/huggingface/diffusers/blob/main/src/diffusers/models/unet_2d_blocks.py#L2546) are pretty similar to `AttnDownsampleBlock2D`/`AttnUpsampleBlock2D` in having a `ResnetBlock2D`/`Attention`/`ResnetBlock2D` downsampler/upsampler pattern. Might it be possible to leverage some or all of the `SimpleCrossAttnDownBlock2D`/`SimpleCrossAttnUpBlock2D` implementation?

These blocks use `AttnAddedKVProcessor`, which has a different Attention implementation, and would have been non-trivial to convert it into what we need without changing the Attention Processor. Also it would be better to keep the Cross-Attention implementations seperate from simple attention imo.

Also the new blocks are simply a copy of `AttnDownBlock2D/AttnUpBlock2D`, with `self.downsamplers/self.upsamplers` being a resnet instead of a simple down/upsampler.

So we can also instead parameterize `AttnDownBlock2D` to have a resnet downsampler instead based on an argument

**Comment by dg845** [comment]
Makes sense, looks good to me then :).

**Pull request merged**
